# Generated by Django 5.2.8 on 2025-11-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='jump_type',
            field=models.CharField(choices=[('simple', 'Simple Jump - Ignore parameters'), ('forward', 'Parameter Forward - Forward all parameters'), ('prefix', 'Prefix Mode - Match paths with this prefix'), ('prefix-forward', 'Prefix + Forward - Match prefix and forward parameters')], default='simple', help_text='Simple: ignore URL parameters. Forward: pass parameters to destination. Prefix: match paths with prefix. Prefix-Forward: combine prefix matching with parameter forwarding', max_length=20),
        ),
    ]
