# Generated by Django 5.2.8 on 2025-11-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_shortlink_jump_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='destination_url',
            field=models.CharField(help_text='The destination URL or URI (supports http://, https://, mailto:, tel:, and custom app protocols)', max_length=2048),
        ),
    ]
